service:
  enable_cors: true
  http_port: 6333
  grpc_port: 6334
  max_request_size_mb: 50
  shutdown_timeout_sec: 30
storage:
  storage_path: "/qdrant/storage"
  on_disk_payload: true
  wal:
    wal_capacity_mb: 512
    wal_segments_ahead: 2
log:
  level: INFO
telemetry_disabled: true
performance:
  max_concurrent_searches: 16
