services:
  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.test.example
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://orchestrator:8000
    depends_on:
      - orchestrator

  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.test.example
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in .env.test.example}@postgres:5432/${POSTGRES_DB:-kyros_test}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:?Please set QDRANT_API_KEY in .env.test.example}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-}@redis:6379
    depends_on:
      - postgres
      - qdrant
      - redis

  terminal-daemon:
    build:
      context: ./services/terminal-daemon
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    env_file:
      - .env.test.example
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:15
    env_file:
      - .env.test.example
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-kyros_test}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in .env.test.example}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    env_file:
      - .env.test.example
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:?Please set QDRANT_API_KEY in .env.test.example}
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env.test.example
    command: >
      sh -c 'if [ -n "${REDIS_PASSWORD:-}" ]; then exec redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"; else exec redis-server --appendonly yes; fi'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  qdrant_data:
  redis_data: