# .gemini/config.yaml
# Gemini 2.5 Pro local usage config. Key is read from GOOGLE_API_KEY env var.
defaults:
  model: "gemini-2.5-pro"
  max_output_tokens: 2048
  style: "surgical_edits"
env:
  key_env: "GOOGLE_API_KEY"
roles:
  implementer:
    temperature: 0.2
    tools: ["tests.run", "git.ops"]
