openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: NextAuth authentication endpoints
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/auth/signin:
    get:
      summary: Sign in page
      responses:
        '200':
          description: Redirect to sign in
  /api/auth/signout:
    post:
      summary: Sign out
      responses:
        '200':
          description: Sign out success
  /api/auth/session:
    get:
      summary: Get current session
      responses:
        '200':
          description: Session data
  /api/auth/[...nextauth]:
    get:
      summary: NextAuth dynamic route
      parameters:
        - name: nextauth
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Auth response
    post:
      summary: NextAuth dynamic route POST
      parameters:
        - name: nextauth
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Auth response