name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Describe the issue here.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: related-prs
    attributes:
      label: Related PRs or tasks
      description: Link to any related PRs or tasks.