name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Describe the feature request here.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe the expected behavior of the feature.
    validations:
      required: true

  - type: textarea
    id: related-prs
    attributes:
      label: Related PRs or tasks
      description: Link to any related PRs or tasks.