# Alert Rules Configuration

rules:
  - name: "Critical Code Quality Threshold"
    description: "Alert when code quality drops below critical threshold"
    metric_pattern: "code_quality"
    condition: "value < threshold"
    threshold: 70.0
    severity: "critical"
    cooldown_period: 300
    enabled: true
    notification_channels: ["slack", "email"]
  
  - name: "Test Coverage Breach"
    description: "Alert when test coverage falls below minimum"
    metric_pattern: "test_coverage"
    condition: "value < threshold"
    threshold: 80.0
    severity: "high"
    cooldown_period: 600
    enabled: true
    notification_channels: ["slack"]
  
  - name: "Security Vulnerability Detected"
    description: "Alert when security vulnerabilities are found"
    metric_pattern: "security_vulnerabilities"
    condition: "value > threshold"
    threshold: 0.0
    severity: "critical"
    cooldown_period: 300
    enabled: true
    notification_channels: ["slack", "email", "webhook"]
  
  - name: "Performance Degradation"
    description: "Alert when performance metrics degrade"
    metric_pattern: "performance"
    condition: "value < threshold"
    threshold: 75.0
    severity: "high"
    cooldown_period: 600
    enabled: true
    notification_channels: ["slack"]
  
  - name: "Architecture Pattern Violation"
    description: "Alert when architecture patterns are violated"
    metric_pattern: "pattern_violations"
    condition: "value > threshold"
    threshold: 2.0
    severity: "medium"
    cooldown_period: 900
    enabled: true
    notification_channels: ["email"]
  
  - name: "Database Connectivity Issues"
    description: "Alert when database connectivity is lost"
    metric_pattern: "database_connectivity"
    condition: "value < threshold"
    threshold: 1.0
    severity: "critical"
    cooldown_period: 300
    enabled: true
    notification_channels: ["slack", "email"]
  
  - name: "High Error Rate"
    description: "Alert when error rate exceeds threshold"
    metric_pattern: "error_rate"
    condition: "value > threshold"
    threshold: 5.0
    severity: "high"
    cooldown_period: 600
    enabled: true
    notification_channels: ["slack"]
  
  - name: "Memory Usage High"
    description: "Alert when memory usage is too high"
    metric_pattern: "memory_usage"
    condition: "value > threshold"
    threshold: 85.0
    severity: "medium"
    cooldown_period: 900
    enabled: true
    notification_channels: ["email"]