# Quality Validation System Configuration

# Database Configuration
database_url: "postgresql://postgres:password@localhost:5432/quality_validation"

# Redis Configuration for caching and real-time monitoring
redis_url: "redis://localhost:6379"

# Monitoring Configuration
monitoring:
  check_interval: 300  # seconds between monitoring checks
  alert_cooldown: 600   # seconds before re-triggering same alert
  anomaly_threshold: 3.0  # Z-score threshold for anomaly detection

# Validation Configuration
validation:
  max_concurrent_tests: 10  # Maximum number of concurrent test executions
  test_timeout: 300        # Default test timeout in seconds
  fail_fast: false        # Stop test suite on first failure

# Benchmarking Configuration
benchmarking:
  historical_data_days: 90     # Days of historical data to keep
  trend_analysis_window: 30     # Days for trend analysis
  percentile_calculation_samples: 100  # Samples for percentile calculations

# Quality Assurance Protocols Configuration
protocols:
  auto_start: true         # Automatically start protocols for validations
  approval_required: true  # Require approvals for protocol completion
  cleanup_days: 30         # Days to keep completed protocol executions

# Alert Rules Configuration (loaded from separate file)
alert_rules_file: "config/alert_rules.yaml"

# Notification Channels Configuration (loaded from separate file)
notification_channels_file: "config/notification_channels.yaml"

# Role-specific thresholds
role_thresholds:
  architect:
    documentation_coverage: 90
    pattern_adherence: 85
    reliability: 95
  
  implementer:
    code_quality: 85
    test_coverage: 80
    maintainability: 75
  
  orchestrator:
    performance: 90
    reliability: 95
    uptime: 99.9
  
  critic:
    security: 95
    compliance: 100
  
  integrator:
    reliability: 98
    performance: 85
    documentation: 80