"""Initial migration for events table.

Note: Uses generic JSON type instead of PostgreSQL-specific JSONB for database
agnosticism. While JSONB offers better indexing and query performance for PostgreSQL,
the JSON type ensures compatibility across different database backends (SQLite, MySQL, etc.).
For PostgreSQL-specific deployments, consider using conditional column types based on
the database backend to leverage JSONB's performance benefits.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
